version: '2.1'

services:

  mongodb:
   build: ./app/mongodb
   container_name: "mongo"
   volumes:
     - ./dbs:/data/db
   networks:
     - backend

  bot:
    build: ./
    container_name: "tgbot"
    ports:
      - 8081:8081
    links:
      - mongodb:mongo
    volumes:
      - /RedmineBot_data/Data/:./FilesFromBot
    depends_on:
      - mongodb
    networks:
      -  backend
    restart: on-failure

networks:
  backend:
    ipam:
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
        ip_range: 10.0.1.2/24
